# Generated by Django 5.2.4 on 2025-12-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetUpload',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('dataset_type', models.TextField()),
                ('format', models.TextField()),
                ('source', models.TextField()),
                ('meta', models.JSONField()),
                ('row_count', models.TextField()),
                ('is_processed', models.BooleanField()),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dataset_upload',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelRouteLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('pipeline', models.CharField(max_length=255, null=True)),
                ('route_mode', models.CharField(max_length=255, null=True)),
                ('rule_output', models.JSONField(null=True)),
                ('llm_output', models.JSONField(null=True)),
                ('chosen_output', models.CharField(max_length=255, null=True)),
                ('diff_summary', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'model_route_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(blank=True, null=True)),
                ('source', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=20)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingSample',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(blank=True, null=True)),
                ('sample_type', models.TextField()),
                ('input_payload', models.JSONField()),
                ('expected_output', models.JSONField()),
                ('rule_output', models.JSONField()),
                ('llm_output', models.JSONField()),
                ('chosen_output', models.TextField()),
                ('is_labeled', models.BooleanField()),
                ('label', models.TextField(blank=True, null=True)),
                ('label_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'training_sample',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HumanLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(choices=[('micro', 'Micro'), ('macro', 'Macro')], max_length=16)),
                ('sample_id', models.UUIDField()),
                ('label_json', models.JSONField()),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('reviewer', models.CharField(max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'human_label',
            },
        ),
        migrations.CreateModel(
            name='PromotionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('micro', 'Micro'), ('macro', 'Macro'), ('rules', 'Rules')], max_length=16)),
                ('target_version', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('requested_by', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed')], default='requested', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'promotion_request',
            },
        ),
    ]
