# Generated by Django 5.2.4 on 2025-12-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetUpload',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('dataset_type', models.TextField()),
                ('format', models.TextField()),
                ('source', models.TextField()),
                ('meta', models.JSONField()),
                ('row_count', models.TextField()),
                ('is_processed', models.BooleanField()),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dataset_upload',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(blank=True, null=True)),
                ('source', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=20)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingSample',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(blank=True, null=True)),
                ('sample_type', models.TextField()),
                ('input_payload', models.JSONField()),
                ('expected_output', models.JSONField()),
                ('rule_output', models.JSONField()),
                ('llm_output', models.JSONField()),
                ('chosen_output', models.TextField()),
                ('is_labeled', models.BooleanField()),
                ('label', models.TextField(blank=True, null=True)),
                ('label_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'training_sample',
                'managed': False,
            },
        ),
    ]
